# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CS193Intent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CS193Intent

end

target 'CS193p' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CS193p
  pod 'CocoaAsyncSocket'

end

target 'CS193pWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaAsyncSocket'

  # Pods for CS193pWidgetExtension

end
